apiVersion: rebalancer.dev/v1
kind: ResourceRebalancer
metadata:
  name: smart-rebalancer
spec:
  userNamespace: "k8s-resource-rebalancer-operator-system"
  cpuThreshold: 50
  memoryThreshold: 500
  enableCleanup: true