apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rebalancer-metrics-auth-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rebalancer-metrics-auth
subjects:
- kind: ServiceAccount
  name: rebalancer-sa
  namespace: system
