blank_issues_enabled: false
contact_links:
  - name: 💬 Questions & Discussions
    url: https://github.com/zeldebro/k8s-resource-rebalancer-operator/discussions
    about: Ask questions and discuss ideas in GitHub Discussions

